spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crud_example
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
        hibernate.hbm2ddl.auto: update
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect